src/Entity/Customer.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CustomerRepository")
 */
class Customer
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CustomerUser", mappedBy="createdBy")
     */
    private $customerUsers;

    /**
     * @ORM\Column(type="date")
     */
    private $date_from;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_to;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Employee", inversedBy="customers")
     */
    private $createdBy;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User", inversedBy="customer", cascade={"persist", "remove"})
     */
    private $compte;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\StrategyDigital", mappedBy="createBy")
     */
    private $strategyDigitals;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $company;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $telephone;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Employee", inversedBy="customersCoach")
     */
    private $coachs;
    use ColunmTrait;
    public function __construct()
    {
        $this->customerUsers = new ArrayCollection();
        $this->strategyDigitals = new ArrayCollection();
        $this->coachs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection|CustomerUser[]
     */
    public function getCustomerUsers(): Collection
    {
        return $this->customerUsers;
    }

    public function addCustomerUser(CustomerUser $customerUser): self
    {
        if (!$this->customerUsers->contains($customerUser)) {
            $this->customerUsers[] = $customerUser;
            $customerUser->setCreatedBy($this);
        }

        return $this;
    }

    public function removeCustomerUser(CustomerUser $customerUser): self
    {
        if ($this->customerUsers->contains($customerUser)) {
            $this->customerUsers->removeElement($customerUser);
            // set the owning side to null (unless already changed)
            if ($customerUser->getCreatedBy() === $this) {
                $customerUser->setCreatedBy(null);
            }
        }

        return $this;
    }

    public function getDateFrom(): ?\DateTimeInterface
    {
        return $this->date_from;
    }

    public function setDateFrom(\DateTimeInterface $date_from): self
    {
        $this->date_from = $date_from;

        return $this;
    }

    public function getDateTo(): ?\DateTimeInterface
    {
        return $this->date_to;
    }

    public function setDateTo(?\DateTimeInterface $date_to): self
    {
        $this->date_to = $date_to;

        return $this;
    }

    public function getCreatedBy(): ?Employee
    {
        return $this->createdBy;
    }

    public function setCreatedBy(?Employee $createdBy): self
    {
        $this->createdBy = $createdBy;

        return $this;
    }

    public function getCompte(): ?User
    {
        return $this->compte;
    }

    public function setCompte(?User $compte): self
    {
        $this->compte = $compte;

        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }

    /**
     * @return Collection|StrategyDigital[]
     */
    public function getStrategyDigitals(): Collection
    {
        return $this->strategyDigitals;
    }

    public function addStrategyDigital(StrategyDigital $strategyDigital): self
    {
        if (!$this->strategyDigitals->contains($strategyDigital)) {
            $this->strategyDigitals[] = $strategyDigital;
            $strategyDigital->setCreateBy($this);
        }

        return $this;
    }

    public function removeStrategyDigital(StrategyDigital $strategyDigital): self
    {
        if ($this->strategyDigitals->contains($strategyDigital)) {
            $this->strategyDigitals->removeElement($strategyDigital);
            // set the owning side to null (unless already changed)
            if ($strategyDigital->getCreateBy() === $this) {
                $strategyDigital->setCreateBy(null);
            }
        }

        return $this;
    }

    public function getCompany(): ?string
    {
        return $this->company;
    }

    public function setCompany(?string $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    /**
     * @return Collection|Employee[]
     */
    public function getCoachs(): Collection
    {
        return $this->coachs;
    }

    public function addCoach(Employee $coach): self
    {
        if (!$this->coachs->contains($coach)) {
            $this->coachs[] = $coach;
        }

        return $this;
    }

    public function removeCoach(Employee $coach): self
    {
        if ($this->coachs->contains($coach)) {
            $this->coachs->removeElement($coach);
        }

        return $this;
    }

}

src/Form/CustomerType.php
<?php

namespace App\Form;

use App\Entity\Customer;
use App\Entity\Employee;
use App\Security\RoleService;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CustomerType extends AbstractType
{
    /**
     * @var RoleService
     */
    private $roles = [];

    public function __construct(RoleService $roles)
    {
        $this->roles = $roles;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date_from', DateType::class, [
                'label' => 'Date De Debut',
                'widget' => 'single_text',
                'html5' => false,
                'required' => false,
            ])
            ->add('date_to', DateType::class, [
                'label' => 'Date De Fin',
                'widget' => 'single_text',
                'html5' => false,
                'required' => false,
            ])
            ->add('name')
            ->add('visible')
            ->add('company')
            ->add('address')
            ->add('telephone')
            ->add('coachs', EntityType::class, [
                'class' => Employee::class,
                'placeholder' => 'Select coach',
                'multiple' => true,
                'attr' => ['class' => 'selectpicker', 'data-size' => 10, 'data-live-search' => true],
            ])
            // ->add('createdBy')
            //->add('compte', new UserType($this->roles))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Customer::class,
        ]);
    }
}

src/Controller/CustomerController.php
<?php

namespace App\Controller;

use App\Entity\Customer;
use App\Form\CustomerType;
use App\Form\UserType;
use App\Repository\CustomerRepository;
use Doctrine\ORM\EntityManagerInterface;
use FOS\UserBundle\Form\Type\ProfileFormType;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/customer")
 * @Security("is_granted('view_customer')")
 */
class CustomerController extends AbstractController
{
    /**
     * @Route("/", name="customer_index", methods={"GET"})
     */
    public function index(CustomerRepository $customerRepository, EntityManagerInterface $manager, PaginatorInterface $paginator, Request $request): Response
    {
        $dql = 'SELECT a FROM App\Entity\Customer a';
        $query = $manager->createQuery($dql);
        $paginator = $paginator->paginate($query, $request->query->getInt('page', 1), 8);

        return $this->render('customer/index.html.twig', [
            'customers' => $paginator,
        ]);
    }

    /**
     * @Route("/new", name="customer_new", methods={"GET","POST"})
     * @Security("is_granted('create_customer')")
     */
    public function new(Request $request): Response
    {
        $customer = new Customer();
        $form = $this->createForm(CustomerType::class, $customer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $customer->setRegisteredAt(new \DateTime('now'));
            $customer->setCreatedBy($this->getUser()->getEmployee());
            $entityManager->persist($customer);
            $entityManager->flush();
            $url = $this->generateUrl('user_new_customer', ['id' => $customer->getId()]);
            $this->addFlash('success', 'Operation effectuée avec success');
            return $this->redirect($url);
        }

        return $this->render('customer/new.html.twig', [
            'customer' => $customer,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="customer_show", methods={"GET"})
     */
    public function show(Request $request, Customer $customer): Response
    {
        $form = $this->createForm(CustomerType::class, $customer);
        $formPassword = $this->createForm(ProfileFormType::class, $customer->getCompte());
        $formUser = $this->createForm(UserType::class, $customer->getCompte());
        $form->handleRequest($request);
        $formPassword->handleRequest($request);
        $formUser->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $url = $this->generateUrl('employee_show', ['id' => $customer->getId()]);

            return $this->redirect($url);
        }

        if ($formUser->isSubmitted() && $formUser->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $url = $this->generateUrl('employee_show', ['id' => $customer->getId()]);

            return $this->redirect($url);
        }

        return $this->render('customer/show.html.twig', [
            'customer' => $customer,
             'strategy_digitals' => $customer->getStrategyDigitals(),
            'form' => $form->createView(),
            'formPassworld' => $formPassword->createView(),
            'formUser' => $formUser->createView(),
            'user' => $customer->getCompte(),
            'nbre_strategiy' => sizeof($customer->getStrategyDigitals()),
            'nbre_customeruser'=>sizeof($customer->getCustomerUsers()),
            'tabs' => [['Information Personnel', '#personnelle'], ['Mon Compte', '#compte']],
        ]);
    }

    /**
     * @Route("/{id}/edit", name="customer_edit", methods={"GET","POST"})
     * @Security("is_granted('edit_customer')")
     */
    public function edit(Request $request, Customer $customer): Response
    {
        $form = $this->createForm(CustomerType::class, $customer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('customer_index');
        }

        return $this->render('customer/edit.html.twig', [
            'customer' => $customer,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="customer_delete", methods={"DELETE"})
     * @Security("is_granted('delete_customer')")
     */
    public function delete(Request $request, Customer $customer): Response
    {
        if ($this->isCsrfTokenValid('delete'.$customer->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($customer);
            $entityManager->flush();
        }

        return $this->redirectToRoute('customer_index');
    }

    /**
     * @Route("/{id}/enable", name="customer_enable", methods={"GET"})
     * @Security("is_granted('edit_customer')")
     */
    public function enableuser(Request $request, Customer $customer): Response
    {
        if ($customer->isVisible()) {
            $customer->setVisible(false);
            $customer->getCompte()->setEnabled(false);
            $this->getDoctrine()->getManager()->flush();
        } else {
            $customer->setVisible(true);
            $customer->getCompte()->setEnabled(true);
            $this->getDoctrine()->getManager()->flush();
        }

        return $this->redirectToRoute('customer_index');
    }
}

templates/customer/_delete_form.html.twig
<form method="post" action="{{ path('customer_delete', {'id': customer.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ customer.id) }}">
    <button class="btn">Delete</button>
</form>

templates/customer/_form.html.twig
{{ form_start(form) }}
<div class="row">
    <div class="col-md-6">
        {{  form_row(form.name) }}
        {{form_row(form.company) }}
        {{  form_row(form.date_from) }}
    </div>
    <div class="col-md-6">
        {{  form_row(form.telephone) }}
        {{  form_row(form.address) }}
        {{  form_row(form.date_to) }}
        {{  form_row(form.visible) }}
    </div>
</div>
    {{ form_widget(form) }}
<div class="pull-right">
    <button type="reset" class="btn btn-warning "><i class="fa fa-times"></i> {{ 'Cancel'|trans }}</button>
    <button type="submit" class="btn btn-primary "><i class="fa fa-arrow-right"></i> {{ button_label|default('Next') }}</button>
</div>
{{ form_end(form) }}

templates/customer/edit.html.twig
{% extends 'base.html.twig' %}
{% block title %}Customer edit{% endblock %}
{% block page_title %} Customer {% endblock %}
{% block page_subtitle %} edit {% endblock %}
{% block page_content %}

    {{ include('customer/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="btn btn-warning" href="{{ path('customer_index') }}"><i class="fa fa-arrow-left"></i></a>

    {{ include('customer/_delete_form.html.twig') }}
{% endblock %}

templates/customer/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Customer index{% endblock %}
{% block page_title %} Customer {% endblock %}
{% block page_subtitle %} list {% endblock %}
{% block page_content %}
    <div class="row">
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
        </div>
        <div class="col-md-3">
            <div class="btn-group pull-right">
                <a class="btn btn-success btn-sm" href="{{ path('customer_new') }}" data-toggle="tooltip" data-placement="top" title="create customer"><i class="fa fa-plus"></i></a>
                <a  class="btn btn-default btn-sm" href="#"><i class="fa fa-download"></i></a>
            </div>
        </div>
    </div>
    <br>
    {% embed '@AdminLTE/Widgets/box-widget.html.twig' %}
        {% block box_before %}{% endblock %}
        {% block box_body %}

    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_from</th>
                <th>Date_to</th>
                <th {% if customers.isSorted('a.Name') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(customers, 'Name', 'a.name') }}</th>

                <th>Visible</th>
                <th>RegisteredAt</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for customer in customers %}
            <tr {% if loop.index is odd %}class="colors"{% endif %}>
                <td>{{ customer.id }}</td>
                <td>{{ customer.dateFrom ? customer.dateFrom|date('Y-m-d') : '' }}</td>
                <td>{{ customer.dateTo ? customer.dateTo|date('Y-m-d') : '' }}</td>
                <td>{{ customer.name }}</td>
                <td>
                    {% if customer.visible %}
                        <a class="btn btn-success btn-xs" href="{{ path('customer_enable', {'id': customer.id}) }}"><i class="fa fa-check-circle"></i></a>
                    {% else %}
                        <a class="btn btn-danger btn-xs" href="{{ path('customer_enable', {'id': customer.id}) }}"><i class="fa fa-times-circle"></i></a>
                    {% endif %}
                </td>
                <td>{{ customer.registeredAt ? customer.registeredAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <div class="btn-group">
                        <a class="btn btn-info btn-sm" href="{{ path('customer_show', {'id': customer.id}) }}" data-toggle="tooltip" data-placement="top" title="show"><i class="fa fa-eye"></i></a>
                        <a class="btn btn-warning btn-sm" href="{{ path('customer_edit', {'id': customer.id}) }}" data-toggle="tooltip" data-placement="top" title="edit"><i class="fa fa-edit"></i></a>
                        {% if customer.visible %}
                            <a class="btn btn-success btn-sm" href="{{ path('customer_enable', {'id': customer.id}) }}"  data-toggle="tooltip" data-placement="top" title="desactiver"><i class="fa fa-check-circle"></i></a>
                        {% else %}
                            <a class="btn btn-danger btn-sm" href="{{ path('customer_enable', {'id': customer.id}) }}"  data-toggle="tooltip" data-placement="top" title="activer"><i class="fa fa-times-circle"></i></a>
                        {% endif %}
                        <a class="btn btn-flat btn-sm" href="#" data-toggle="tooltip" data-placement="top" title="delete"><i class="fa fa-trash-alt"></i></a>
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
            <div class="navigation">
                {{ knp_pagination_render(customers) }}
            </div>
{% endblock %}

{% endembed %}
{% endblock %}

templates/customer/new.html.twig
{% extends 'base.html.twig' %}
{% block title %}Customer new{% endblock %}
{% block page_title %} Customer {% endblock %}
{% block page_subtitle %} new {% endblock %}
{% block page_content %}
{% embed '@AdminLTE/Widgets/box-widget.html.twig' %}
                {% block box_before %}{% endblock %}
                {% block box_body %}
    {{ include('customer/_form.html.twig') }}
                {% endblock %}
    {% block box_footer %}

    {% endblock %}

    {% block box_after %}{% endblock %}
{% endembed %}
    <a class="btn btn-warning" href="{{ path('customer_index') }}" data-toggle="tooltip" data-placement="top" title="Back customer"><i class="fa fa-arrow-left"></i></a>

{% endblock %}

templates/customer/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Customer{% endblock %}
{% block page_title %} Customer {% endblock %}
{% block page_subtitle %} Details {% endblock %}
{% block page_content %}

    <div class="row">
        <div class="col-md-3">
            {% embed '@AdminLTE/Widgets/box-widget.html.twig' %}
                {% block box_before %}{% endblock %}
                {% block box_body %}
                    <div class="text-center">
                        <img class="profile-user-img img-fluid img-circle"
                             src="{{ asset('bundles/adminlte/images/default_avatar.png') }}"
                             alt="User profile picture">
                    </div>
                    <h3 class="profile-username text-center">{{ user.username }}</h3>

                    <p class="text-muted text-center">{{ user.email}}</p>
                    <ul class="list-group list-group-unbordered mb-3">
                        <li class="list-group-item">
                            <b>Strategy Digital</b> <a class="float-right">{{ nbre_strategiy }}</a>
                        </li>
                        <li class="list-group-item">
                            <b>Customer user</b> <a class="float-right">{{ nbre_customeruser }}</a>
                        </li>
                    </ul>

                {% endblock %}

                {% block box_after %}{% endblock %}
            {% endembed %}
        </div>
        <div class="col-md-9">
            <div class="row">
                <div class="col-md-12">
                    {% embed '@AdminLTE/Widgets/box-widget.html.twig' %}
                        {% block box_before %}{% endblock %}
                        {% block box_body %}
                            <ul class="nav nav-pills">
                                {% for tab in tabs %}
                                    <li class="nav-item"><a class="nav-link active" href="{{tab[1]}}" data-toggle="tab">{{tab[0]  }}</a></li>
                                {% endfor %}
                            </ul>
                            <div class="tab-content">
                                <div class="active tab-pane" id="personnelle">
                                    {{ include('customer/_form.html.twig', {'button_label': 'Update'}) }}
                                    <br>
                                </div>

                                {#gestion compte#}
                                <div class="tab-pane" id="compte">
                                    {{ form_start(formUser) }}
                                    <div class="col-md-6">
                                        {{ form_row(formUser.username) }}
                                        {{ form_row(formUser.email) }}
                                    </div>
                                    <div class="col-md-6">
                                        {{ form_row(formUser.plainPassword) }}
                                    </div>
                                    {{ form_widget(formUser) }}

                                    <div class="pull-right">
                                        <button type="reset" class="btn btn-warning "><i class="fa fa-times"></i> {{ 'Cancel'|trans }}</button>
                                        <button type="submit" class="btn btn-primary "><i class="fa fa-check-square"></i> {{ button_label|default('Save') }}</button>
                                    </div>
                                    {{ form_end(form) }}
                                </div>

                            </div>
                        {% endblock %}

                        {% block box_after %}{% endblock %}
                    {% endembed %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}